export const CUSTOMER_INTENT = Object.freeze({
  VIEW_MENU: "VER_MENU",
  ADD_PRODUCT: "AGREGAR_PRODUCTO",
  REMOVE_PRODUCT: "QUITAR_PRODUCTO",
  MODIFY_PRODUCT: "MODIFICAR_PRODUCTO",
  ASK_TOTAL: "PEDIR_TOTAL",
  CONFIRM_ORDER: "CONFIRMAR_PEDIDO",
  CANCEL_ORDER: "CANCELAR_PEDIDO",
  ASK_HOURS: "CONSULTAR_HORARIO",
  ASK_DELIVERY: "CONSULTAR_ENVIO",
  SEND_ADDRESS: "ENVIAR_DIRECCION",
  CHOOSE_PICKUP: "ELEGIR_RETIRO",
  CHOOSE_DELIVERY: "ELEGIR_DELIVERY",
  CHOOSE_PAYMENT: "ELEGIR_FORMA_PAGO",
  TALK_TO_HUMAN: "HABLAR_CON_PERSONA",
  UNKNOWN: "NO_ENTENDIDO"
});

export function isValidCustomerIntent(intent) {
  return Object.values(CUSTOMER_INTENT).includes(intent);
}
