export const ORDER_STATUS = Object.freeze({
  CREATED: "CREADO",
  BUILDING: "ARMANDO_PEDIDO",
  WAITING_CONFIRMATION: "ESPERANDO_CONFIRMACION",
  WAITING_PAYMENT: "ESPERANDO_PAGO",
  PAID: "PAGADO",
  IN_PREPARATION: "EN_PREPARACION",
  READY: "LISTO",
  ON_THE_WAY: "EN_CAMINO",
  DELIVERED: "ENTREGADO",
  CANCELLED: "CANCELADO",
  ERROR: "ERROR",
  REQUIRES_HUMAN: "REQUIERE_HUMANO"
});

export function isValidOrderStatus(status) {
  return Object.values(ORDER_STATUS).includes(status);
}
